repos:
  - repo: local
    hooks:
      - id: make-style
        name: make style
        entry: make style
        language: system
      - id: terraform-fmt
        name: terraform fmt
        entry: bash -c 'terraform -chdir=terraform fmt -recursive'
        language: system
  - repo: https://github.com/python-poetry/poetry
    rev: 1.6.1
    hooks:
      - id: poetry-check
      - id: poetry-lock
        args: ["--no-update"]
      - id: poetry-export
        args: ["--with", "training", "-f", "requirements.txt", "-o", "training/requirements.txt"]
      - id: poetry-export
        args: ["--with", "frontend", "-f", "requirements.txt", "-o", "frontend/requirements.txt"]